headers = ['RECORD ID',
           'CLIENT CODE',
           'VENDOR CODE',
           'RATE TYPE',
           'EXTERNAL RATE SOURCE',
           'MODE',
           'EQUIPMENT',
           'ROUTE',
           'FUEL PROGRAM',
           'ROUND TRIP',
           'INCOTERMS',
           'FREIGHT TERMS',
           'NOTES',
           'GEOGRAPHY EXCLUSION',
           'ORIGIN LOCATION CODE',
           'ORIGIN REGION',
           'ORIGIN CITY',
           'ORIGIN COUNTY',
           'ORIGIN STATE',
           'ORIGIN ZIP',
           'ORIGIN ZIP RANGE',
           'ORIGIN COUNTRY',
           'DESTINATION LOCATION CODE',
           'DESTINATION REGION',
           'DESTINATION CITY',
           'DESTINATION COUNTY',
           'DESTINATION STATE',
           'DESTINATION ZIP',
           'DESTINATION ZIP RANGE',
           'DESTINATION COUNTRY',
           'EFFECTIVE DATE',
           'EXPIRATION DATE',
           'LOAD ID',
           'CHARGETYPE',
           'UOM',
           'INSTANCE',
           'AUTO APPLY',
           'APPLY AT LEVEL',
           'BAND UOM MIN',
           'BAND UOM MAX',
           'FLAT CHARGE',
           'RATE',
           'MINIMUM CHARGE',
           'MAXIMUM CHARGE',
           'BASE CHARGE',
           'EXCESS RATE',
           'DISCOUNT RATE',
           'CURRENCY CODE',
           'ALLOW DEFICIT',
           'ALLOW HIGHER DOWN',
           'AUTHORITY PUBLISHER',
           'AUTHORITY RELEASE',
           'AUTHORITY SECTION',
           'AUTHORITY ITEM',
           'AUTHORITY EFFECTIVE DATE',
           'AUTHORITY EXPIRATION DATE',
           'LOW COMMODITY CODE',
           'HIGH COMMODITY CODE',
           'LOW CLASS',
           'HIGH CLASS',
           'AS CLASS',
           'CONSTRAINT', ]
